:PROPERTIES:
:ID:       2ae9872a-5879-4c00-921c-aeffefd7e01d
:END:
#+title: Spectro et bioinfo
#+filetags: :meeting:
[[id:b08807ac-d9e3-4987-8b42-be4ec686d94c][Deep learning]] [[id:14805012-e9b8-491a-9b56-c4830c1d9685][image fusion]] [[id:fc865bc6-4c84-4d9f-8d67-21980ff47424][MSI]] [[id:9a753b0f-254a-42cf-8ef4-9b139a0bd14f][Raman imaging]]

_Participants_: Sophie Lecomte, Jean-Christophe Taveau, Nicolas Desbenoit, Raluca Uricaru, Patricia Thébault, Joris Sansen, Olivier Lambert.

Tour de table de chaque intervenant.

Deux initiatives:
- Sophie: ajouter du Machine Learning
- Patricia: réunir la communauté bioinfo

_Raman_: projet de stage → import/export fichiers, outils de pré-traitement Raman.
L'objectif est d'ajouter du Machine Learning, plus précisément du Deep Learning. Détection d'Aluminium dans des cellules. Les données initiales ne donnent aucune certitude quant à la présence d'Aluminium (signature spectrale incertaine). Besoin de s'en assurer: recours à une autre modalité d'imagerie.

Autre blocage pour implémenter Deep Learning: quelle quantité de données? (SL insiste sur ce point)
Pistes: utilisation de transfer learning (à partir d'autres réseaux tels que [[cite:&Horgan2021]].

_Ramanomique_: corrélation entre résultats de transcriptomique et spectre Raman.
⚠ Il ne s'agit plus d'imagerie.

_Recalage_: des approches Deep Learning ont-elles été envisagées?

_TODOs:_
  - Développer deux approches complémentaires pour le traitement et l'interprétation Raman: (1) Deep Learning, et (2) fusion d'images avec imagerie par spectrométrie de masse
    Pour le Deep Learning, les outils de visualisation et d'interprétation des réseaux de neurones semble pertinents (en particulier dans les cas de transfer learning).
  - Jeu de données Raman + MSI
  - PT, RU: plutôt aspect ramanomique → développement d'une collaboration LaBRI-CBMN.
   
    
