:PROPERTIES:
:ID:       2c490269-aa92-47de-9619-614c147b5717
:END:
#+title: Mini-review Frontiers
[[id:a259fda8-0eba-468f-b331-a33a4030074a][MALDI]] [[id:fc865bc6-4c84-4d9f-8d67-21980ff47424][MSI]]

MALDI-MSI Towards Multimodal Imaging: Current challenges and perspectives.

* Introduction
- [[cite:&Qin2018-recen]]
  Recent advances for Plant Sciences: more focused on the application and samples.
- [[cite:&Alexandrov2012-maldi]]
  For data processing
- [[cite:&Nimesh2013-curren]]
  Status of MALDI-MSI. In 2013 → what changed since?

  Overall, current advances are dependent on the field of study, or the application. An overview of current advances of all related methods pertaining to the technique is necessary, similar to [[cite:&Buchberger2017-mass]].
* Current challenges
** Data processing
*** [[id:818a1c5c-937a-40ab-b18d-92e1f49f8a75][Large size]]
**** Format
[[id:82fbac32-a53c-4862-bfe2-4ca99fbd93fe][Memory-mapped files]] seem like a promising approach.
Discussion about imzML.

**** Data reduction
- Dimension reduction: PCA, tSNE, ...
- Data reduction: binning, peak picking, realignment...
  
**** Visualization
- [[id:e1ff9683-0500-4c27-8d89-80377b282049][Kendrick Plot]][[cite:&Buchberger2017-mass]]
- Similarity, see [[cite:&Wuellems2021-fast]]
  
*** [[id:5636efa1-0947-4ff7-a6de-e1e25631ec11][Normalization]]
TIC insufficient → NIC
*** Other optional talking-points
**** [[id:b962b560-9c85-4e67-849b-4f848e6376ec][Quality assurance]]
**** [[id:b46c43ee-9b6d-4845-bd81-ceb93f9e1bad][Signal modelling]]
**** [[id:b08807ac-d9e3-4987-8b42-be4ec686d94c][Deep learning]]
**** [[id:55127251-aa8c-4efc-8462-ad9786f3f59b][Spatial resolution]] determination
** Multimodal imaging
*** Different types of images
1. One-channel image
2. Multi-channel image
3. Hyperspectral image
*** [[id:42cc18b8-69d4-439d-b5f5-f0b61862b79a][Segmentation]]
Different approaches:
- Select an ion image manually
- Clustering: how to compare spectra?
- Dimension reduction methods: PCA, t-SNE...
- DL?
 Depends on the content of the image.
*** [[id:08e9482a-8139-41ee-bac5-ce37fbb4b335][Registration]]
Different methods depending on the image type, and the previous segmentation step.

If the intensities of the object are similar → iconic approaches.
Else if the shape of the object are similar → geometrical based approaches.
Else if nothing else: fiducial. Works for [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][partial registration]].

*** [[id:ba127266-5e70-4a55-ba15-76f57cee2376][Standardization]]
The images need to be on the same intensity scale.
*** [[id:74e38001-568b-42ec-a8f2-bb8a4f39013a][Statistical analysis]]
**** [[id:ac8d4e14-61f1-4b37-8829-186b6938f4ca][Multiblock]]
**** Correlation tools: [[id:bff5b127-ba4d-4d96-b125-4a892f587375][ROC]]
**** [[id:6240f4e3-d85f-404f-823c-187cec75fce2][Statistical methods with uncertainty]]
**** Classical dimension reduction methods: PCA, NMF, ICA...
** Prospects
*** [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][Partial registration]], [[id:13b1dba3-aa5c-453d-be49-a7c06687bb26][3D MSI]].

* Detailed outline

** Generic methods
*** Formats and data representation
A lot of different imaging formats. Sometimes specific to the imaging technique. Difficulty to handle proprietary formats: multiple converters.

imzML is established as the most common format for mass spectrometry imaging datasets. See [[cite:&Schramm2012-imzml]].

Problem caused by the large dataset size of  hyperspectral images such as MSI and Raman.
[[id:82fbac32-a53c-4862-bfe2-4ca99fbd93fe][Memory-mapped files]] seem like a promising approach. Yet, no development made by the MSI community on these approaches. Involve a lot of work to rewrite libraries.

Need for a unique format.

*** Visualization
The nature of the MSI data is complex. Before further processing and choose appropriate methods, it is often desirable to understand the underlying data. Various visualization approaches can be used to investigate the data:
- Mean, max, min spectrum
- [[id:e1ff9683-0500-4c27-8d89-80377b282049][Kendrick Plot]][[cite:&Buchberger2017-mass]]
- Similarity, see [[cite:&Wuellems2021-fast]]
*** Reduction/Segmentation
The purpose is to have images which are comparable in different modalities.
In this section, we focus on methods which are compatible with MSI datasets.

The large dataset size makes the MSI datasets difficult to analyze in a multimodal setting.

 The choice of the method depends on the content of the image.

Various approaches are designed to reduce the complexity of the datasets:
- _Preprocessing_: binning, peak picking, alignment (centroiding)...
- _Select_ an ion image manually
- _Dimension reduction_: PCA, tSNE, ... [[cite:&Abdelmoula_2019]] and [[cite:&Verbeeck_2017]]
- _Spectral clustering_: hierarchical clustering, k-means, method integrating noise by [[cite:&Alexandrov_2011]]. _Issue:_ how to compare spectra?
- Deep Learning techniques
  
** Multimodal methods
*** Different types of images
Different categories depending on the nature of the image, as well as the number of channels in the image.
_Nature of the images_:
1. Anatomical structures : CT, MRI, H&E
2. Chemical structures: MSI, Raman

_Number of channels_:  
1. One-channel image: MRI, CT
2. Multi-channel image: RGB images (H&E), fluorescence microscopy
3. Hyperspectral image: MSI, Raman
   
*** [[id:08e9482a-8139-41ee-bac5-ce37fbb4b335][Registration]]
Different methods depending on the image type, and the previous segmentation step.

Which images to register: usually the one with the lowest resolution.
Increasing the resolution of a low-resolution hyperspectral image might cause memory issues. See discussion in "Reduction".

If the intensities of the object are similar → iconic approaches.
Else if the shape of the object are similar → geometrical based approaches.
Else if nothing else: fiducial. Works for [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][partial registration]].

*** [[id:74e38001-568b-42ec-a8f2-bb8a4f39013a][Statistical analysis]]
**** [[id:ba127266-5e70-4a55-ba15-76f57cee2376][Standardization]]
The images need to be on the same intensity scale.
**** Correlation tools: [[id:bff5b127-ba4d-4d96-b125-4a892f587375][ROC]], Spearman or Pearson's correlation coefficient, cosine similarity...
**** Classical dimension reduction methods: PCA, NMF, ICA...
**** [[id:6240f4e3-d85f-404f-823c-187cec75fce2][Statistical methods with uncertainty]]
**** [[id:ac8d4e14-61f1-4b37-8829-186b6938f4ca][Multiblock]]
** Prospects
*** [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][Partial registration]], [[id:13b1dba3-aa5c-453d-be49-a7c06687bb26][3D MSI]].
