:PROPERTIES:
:ID:       a0cf98b4-cd90-49fc-ba0a-60896e2770db
:END:
#+title: CATI
[[id:2dff42d8-b57a-4c3a-8619-3bfde728f67e][meeting]]

* <2021-11-23 Tue> :multiblock:statisticalanalysis:
:PROPERTIES:
:ID:       5343a1a6-6c81-40b4-8828-1e863d25572a
:ROAM_ALIASES: "CATI Novembre"
:END:
[[id:74e38001-568b-42ec-a8f2-bb8a4f39013a][Statistical analysis]] [[id:ac8d4e14-61f1-4b37-8829-186b6938f4ca][Multiblock]]
** Présentation de Marion Brandolini
Présentation générale.

Données multiblocs: données multivariées, multi-sources, souvent sur mêmes échantillons.
Plusieurs matrices 2D, une seule matrice 2D (plusieurs conditions expérimentales...)

_Principe:_ rechercher des variables latentes (combinaisons linéaires de variables initiales)

Pré-traitement des données:
1. Intrabloc: correction de dérive analytique, normalisation, standardisation des variables (ex: centrage-réduction)
2. Interblocs: Standardisation des blocs: pour éviter leurs différences de taille.

*** Méthodes

**** Multiblocs exploratoire
Décomposition des données en variables latentes: /scores/ et /loadings/. Prise en compte de l'information commune ou non.

Méthodes prenant en compte l'info commune:
- ACP multibloc, ou ACP consensus. Concaténation des blocs pré-traités et pondérés, puis ACP.
- CSWA ou ComDim: extraction /séquentielle/ des composantes maximisant la variance de la somme pondérée des matrices de variance covariances des différents blocs
- RGCCA: voir présentation suivante.
  
Méthodes prenant en compte l'info différente:
- Orthogonal2 PLS (O2PLS) dans le cas de 2 blocs
  espace de données dépourvu de l'espace en commun, uniquement l'information qui est propre aux blocs, puis commune.
- JIVE (Joint and Individual variances explained): idem à plus haut, sauf que d'abord info commune, puis distincte.

**** Multiblocs prédictif
Extraire l'info commune ou complémentaire pour la prédiction

- PLS multiblocs (MBPLS): régression PLS sur blocs prétraités pondérés concaténés
- PLS consensus ou hiérarchique (HPLS): ACP consensus, normalisation des composantes globales, puis PLS.

Différences algos:
- critère à maximiser: variance, covariance, corrélation.
- Normalisation

**** Autres
- Méthodes pour sélection de variables: méthodes sparse
- Méthodes pour données 3D
  
*** Mise en oeuvre
Analyse séparée des blocs
Très grande importance prétraitement des blocs
Optimisation de paramètres (nombre de composantes)

Plusieurs packages R à disposition: mixOmics, RGCCA, multiblock... 

** Présentation Caroline Peltier

Données de spectrométrie de masse, pour DMLA.

_Données_: une observation commune à tous les blocs : données lipidomiques, concentration en ions.
_Blocs_: rétine, zone de rétine (RPE), sang (plasma) et données cliniques.

Coupler analyse sensorielle et analyse physico-chimique.

1. Avoir des blocs de mesures "propres": pas de valeurs manquantes, retirer variables sans sens.
2. Connaître ses blocs séparément (ACP) pour repérer outliers, groupes, retrait de variables individus non renseignés.
3. Pré-traitement pour comparer les blocs de mesures entre eux: passage au log, gestion des valeurs manquantes
4. Bien poser sa question de recherche: exploratoire ou prédictive?

*** _Méthode_
RGCCA

Donner le même poids à tous les blocs, pour éviter qu'un bloc avec beaucoup de variables ait plus de poids qu'un bloc avec peu de variables.

Rechercher un axe par bloc sur lequel projeter pour maximiser un critère.

Déflation pour obtenir plusieurs axes par bloc.
   
** Présentation Marie Tremblay-Franco
Données de métabolomique et lipidomique

_Problème_: variabilité biologique: expérimentale, physiologie, instrumentale
→ Suppression de la variabilité orthogonale (non corrélée).

Méthode DIABLO, extension de sGCCA à la classification.



