:PROPERTIES:
:ID:       487a0644-4a16-4488-a67c-a18925645080
:ROAM_REFS: cite:Wuellems2021-fast
:END:
#+title: Fast visual exploration of mass spectrometry images with interactive dynamic spectral similarity pseudocoloring
#+filetags: :literature:

[[id:bef83f14-66c4-4c3f-8adb-5d0084987f17][Visualization]] of [[id:fc865bc6-4c84-4d9f-8d67-21980ff47424][MSI]] dataset encompassing spectral similarities or dissimilarities.

Two new tools:
- ProVIM: processing of MSI dataset
  - Spectra alignment and normalization
  - Hotspot and matrix removal
    Done by dimension reduction, more specifically UMAP. Important to remove hotspots since they have a large distance in the UMAP embedding wrt to other points.
    _Approach_:
    1. UMAP decomposition
    2. Artifacts and matrix signals are detected either automatically or manually. Automatic detection involves using clustering by k-nearest neighbors and radius neighbor search. If the number of connected components is greater than two, then the smaller component correspond to matrix pixels.
    3. Subtract the mean spectrum of matrix pixels from other spectrum.
  - Peak picking and deisotoping
    Combination of local maxima and threshold based values.
- QUIMBI: interactive visualization tool
Different visualization modes: similarity, browsing, and grouping.
1. Similarity
   Select a reference pixel, then other pixels are compared to the reference using the inverse angular distancec between both spectra (=inverse of the cosine distance?)
2. Browsing
   Select a /m/z/ ratio in the mass spectrum
3. Grouping
   Select *several* /m/z/ ratio in the mass spectrum, the mean intensities are displayed.



