:PROPERTIES:
:ID:       2c490269-aa92-47de-9619-614c147b5717
:END:
#+options: num:nil
#+title: Mini-review Frontiers
[[id:a259fda8-0eba-468f-b331-a33a4030074a][MALDI]] [[id:fc865bc6-4c84-4d9f-8d67-21980ff47424][MSI]]

MALDI-MSI Towards Multimodal Imaging: Current challenges and perspectives.

* Introduction
- [[cite:&Qin2018-recen]]
  Recent advances for Plant Sciences: more focused on the application and samples.
- [[cite:&Alexandrov2012-maldi]]
  For data processing
- [[cite:&Nimesh2013-curren]]
  Status of MALDI-MSI. In 2013 → what changed since?

  Overall, current advances are dependent on the field of study, or the application. An overview of current advances of all related methods pertaining to the technique is necessary, similar to [[cite:&Buchberger2017-mass]].
* Current challenges
** Data processing
*** [[id:818a1c5c-937a-40ab-b18d-92e1f49f8a75][Large size]]
**** Format
[[id:82fbac32-a53c-4862-bfe2-4ca99fbd93fe][Memory-mapped files]] seem like a promising approach.
Discussion about imzML.

**** Data reduction
- Dimension reduction: PCA, tSNE, ...
- Data reduction: binning, peak picking, realignment...
  
**** Visualization
- [[id:e1ff9683-0500-4c27-8d89-80377b282049][Kendrick Plot]][[cite:&Buchberger2017-mass]]
- Similarity, see [[cite:&Wuellems2021-fast]]
  
*** [[id:5636efa1-0947-4ff7-a6de-e1e25631ec11][Normalization]]
TIC insufficient → NIC
*** Other optional talking-points
**** [[id:b962b560-9c85-4e67-849b-4f848e6376ec][Quality assurance]]
**** [[id:b46c43ee-9b6d-4845-bd81-ceb93f9e1bad][Signal modelling]]
**** [[id:b08807ac-d9e3-4987-8b42-be4ec686d94c][Deep learning]]
**** [[id:55127251-aa8c-4efc-8462-ad9786f3f59b][Spatial resolution]] determination]
** Multimodal imaging
*** Different types of images
1. One-channel image
2. Multi-channel image
3. Hyperspectral image
*** [[id:42cc18b8-69d4-439d-b5f5-f0b61862b79a][Segmentation]]
Different approaches:
- Select an ion image manually
- Clustering: how to compare spectra?
- Dimension reduction methods: PCA, t-SNE...
- DL?
 Depends on the content of the image.
*** [[id:08e9482a-8139-41ee-bac5-ce37fbb4b335][Registration]]
Different methods depending on the image type, and the previous segmentation step.

If the intensities of the object are similar → iconic approaches.
Else if the shape of the object are similar → geometrical based approaches.
Else if nothing else: fiducial. Works for [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][partial registration]].

*** [[id:ba127266-5e70-4a55-ba15-76f57cee2376][Standardization]]
The images need to be on the same intensity scale.
*** [[id:74e38001-568b-42ec-a8f2-bb8a4f39013a][Statistical analysis]]
**** [[id:ac8d4e14-61f1-4b37-8829-186b6938f4ca][Multiblock]]
**** Correlation tools: [[id:bff5b127-ba4d-4d96-b125-4a892f587375][ROC]]
**** [[id:6240f4e3-d85f-404f-823c-187cec75fce2][Statistical methods with uncertainty]]
**** Classical dimension reduction methods: PCA, NMF, ICA...
** Prospects
*** [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][Partial registration]], [[id:13b1dba3-aa5c-453d-be49-a7c06687bb26][3D MSI]].

* Detailed outline
** Generic methods
*** Formats and data representation
A lot of different imaging formats. Sometimes specific to the imaging technique. Difficulty to handle proprietary formats: multiple converters.

imzML is established as the most common format for mass spectrometry imaging datasets. See [[cite:&Schramm2012-imzml]].

Problem caused by the large dataset size of  hyperspectral images such as MSI and Raman.
[[id:82fbac32-a53c-4862-bfe2-4ca99fbd93fe][Memory-mapped files]] seem like a promising approach. Yet, no development made by the MSI community on these approaches. Involve a lot of work to rewrite libraries.

Need for a unique format.

*** Visualization
The nature of the MSI data is complex. Before further processing and choose appropriate methods, it is often desirable to understand the underlying data. Various visualization approaches can be used to investigate the data:
- Mean, max, min spectrum
- [[id:e1ff9683-0500-4c27-8d89-80377b282049][Kendrick Plot]][[cite:&Buchberger2017-mass]]
- Similarity, see [[cite:&Wuellems2021-fast]]
- HSNE, see [[cite:&Abdelmoula2018-inter]]
*** Reduction/Segmentation
The purpose is to have images which are comparable in different modalities.
In this section, we focus on methods which are compatible with MSI datasets.

The large dataset size makes the MSI datasets difficult to analyze in a multimodal setting.

 The choice of the method depends on the content of the image.

Various approaches are designed to reduce the complexity of the datasets:
- _Preprocessing_: binning, peak picking, alignment (centroiding)...
- _Select_ an ion image manually
- _Dimension reduction_: PCA, tSNE, ... [[cite:&Abdelmoula_2019]] and [[cite:&Verbeeck_2017]]
- _Spectral clustering_: hierarchical clustering, k-means, method integrating noise by [[cite:&Alexandrov_2011]]. _Issue:_ how to compare spectra?
- Deep Learning techniques
  
** Multimodal methods
*** Different types of images
Different categories depending on the nature of the image, as well as the number of channels in the image.
_Nature of the images_:
1. Anatomical structures : CT, MRI, H&E
2. Chemical structures: MSI, Raman

_Number of channels_:  
1. One-channel image: MRI, CT
2. Multi-channel image: RGB images (H&E), fluorescence microscopy
3. Hyperspectral image: MSI, Raman
   
*** [[id:08e9482a-8139-41ee-bac5-ce37fbb4b335][Registration]]
Different methods depending on the image type, and the previous segmentation step.

Which images to register: usually the one with the lowest resolution.
Increasing the resolution of a low-resolution hyperspectral image might cause memory issues. See discussion in "Reduction".

If the intensities of the object are similar → iconic approaches.
Else if the shape of the object are similar → geometrical based approaches.
Else if nothing else: fiducial. Works for [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][partial registration]].

Raman, MRI, Microscopy, CT + MALDI, SIMS, DESI, LA
1. Fiducial:  [[cite:&Bocklitz_2013]] (Raman/H&E). [[cite:&Borodinov_2020]] (SIMS), [[cite:&Patterson_2018]] (Microscopy), [[cite:&Ryabchykov_2018]] (Raman)
2. Iconic: [[cite:&Patterson_2018]] (Microscopy), [[cite:&Castellanos_Garcia_2021]] (LA-ICP), [[cite:&Verbeeck_2017]] (MRI)
3. Geometrical/shape: [[cite:&Abdelmoula_2019]]  (MRI), [[cite:&Wehrli2020-spatial]] (H&E), [[cite:&Anyz_2017]] (H&E). 
   
*** [[id:74e38001-568b-42ec-a8f2-bb8a4f39013a][Statistical analysis]]
**** [[id:ba127266-5e70-4a55-ba15-76f57cee2376][Standardization]]
The images need to be on the same intensity scale.
**** Correlation tools: [[id:bff5b127-ba4d-4d96-b125-4a892f587375][ROC]], Spearman or Pearson's correlation coefficient, cosine similarity...
**** Classical dimension reduction methods: PCA, NMF, ICA...
**** [[id:6240f4e3-d85f-404f-823c-187cec75fce2][Statistical methods with uncertainty]] [[cite:&Alexandrov2012-maldi]]
**** [[id:ac8d4e14-61f1-4b37-8829-186b6938f4ca][Multiblock]] [[cite:&Wehrli2020-spatial]]
**** [[id:6df664eb-63ad-4ef6-af19-bfa17690d3a9][Machine learning]] [[cite:&Ovchinnikova_2020]]
** Prospects
*** [[id:50bc746a-483e-4beb-97fb-b96833b5cb46][Partial registration]], [[id:13b1dba3-aa5c-453d-be49-a7c06687bb26][3D MSI]].
* Writing
** Introduction
*** Data analysis/statistics
MALDI-MS images are difficult to analyze due to their large size. Various approaches are designed to reduce their complexity.
For instance, peak picking and alignment reduce the dataset size while preserving relevant information along the spectral dimension ([[cite:&Alexandrov2012-maldi]]).
The dataset can be further reduced by dimension reduction techniques, such as PCA ([[cite:&Trindade_2018a]]), NMF (non-negative matrix factorization, [[cite:&Trindade_2018b]]) or t-SNE ([[cite:&Vandermaaten_08a]]). PCA and NMF are linear matrix decomposition techniques, whereas t-SNE is a probabilistic, non-linear dimension reduction technique. PCA and NMF decompose the original, large, MALDI-MS image into two smaller matrices, whose product approximates the original image. Common global information shared across ion images are stored in so-called component images. The component images usually highlight important structures in the tissue. PCA scores give the ion images which are most associated to each component image, enabling to couple spatial information with spectral information. NMF differs from PCA in that it imposes a non-negativity constraint on the components, which makes them easier to interpret. By contrast to PCA and NMF, t-SNE retains local structures by preserving distances between points in a lower-dimensional embedding. This reduction makes for visualizations that are faithful to the original image data. However, the resulting mapping is different across multiple runs, harder to explain and the required computational resources are significantly larger than for PCA. For MALDI-MS images, it is often required to apply PCA so as to reduce the dimensionality, before using t-SNE. [[cite:&Abdelmoula2018-inter]] used a variant of t-SNE, called hierarchical SNE ([[cite:&Pezzotti_2016]]), to visualize structures with different levels of details across ion images.

Clustering methods give simplified representations of the datasets, where similar spectra are grouped together. The output can be visualized as a 2D image where each pixel has an intensity equal to its cluster number. Similarities between spectra can be estimated by various metrics, such as the Euclidean distance, which captures similarities among raw intensities, or the cosine distance, which captures similar trends in the spectra. The k-means algorithm groups spectra according to a predefined number of clusters ([[cite:&Palmer_2014]]), whereas hierarchical clustering yields a hierarchy of clusters, arranged from broad structures to finer details ([[cite:&Urbini_2017]]). [[cite:&Alexandrov_2011]] propose a clustering algorithm which limits the impact of noise in MALDI-MS images, where pixels are grouped by the similarity between their neighborhoods.

In other hand to Validate of statistical differences between samples, ROI or ions distribution, univariate analysis are required. The choose of this univariate analysis will depend on the MSI dataset and the hypothesis of the experiment. T-test demonstrates quantitative differences for a specific m/z between two different samples [[cite:&Yajima_2018]], or regions within a tissue section, whereas  analysis of variance (ANOVA) test can be used to compare three or more regions [[cite:&Blanc_2018]]. In case of non-Gaussian distribution, common in MSI dataset, Mann-Whitney U-Test should then be performed [[cite:&Guo_2014]]. To determine if an ion is a good biomarker to distinguish different conditions ROC curve analysis should be applied to determine the statistical difference [[cite:&Hoo_2017]].
** Pre-processing
:PROPERTIES:
:ID:       e44916fd-cee4-48a8-845d-a4b51fd5a6d8
:END:
There are multiple methods for pre-processing the images, which are often dependent on the modality. In this section, we focus on common pre-processing tasks which facilitate the registration process.

Denoising is commonly applied to remove spurious signal from images. Generic methods, such as median or gaussian filtering, can help to get rid of general intensity irregularities.


** Registration
Registration is usually the first step of multimodal image integration. It consists in aligning two or more images, such that the enclosed objects are superimposed. Registration methods aim at estimating the transformation which maps a moving, or deformable image onto a fixed, or reference image. The images involved can be selected manually (ion image in MALDI) or come from a pre-processing step: component image from dimension reduction techniques, cluster image, or from any segmentation algorithm (see Section [[*Pre-processing][Pre-processing]]). Usually, the moving image is chosen as the one with the lowest resolution, so as to preserve the data from the fixed image with higher resolution. The transformation can be rigid (translation and rotation), affine (rigid with scaling, and shearing), projective (affine with perspective) or non-linear. Non-linear models account for local deformations in the image. They are necessary to accurately model the deformations induced during sample preparation, such as slicing or enzymatic digestion of the tissue.

Registration methods can be classified in two categories, depending on the information they use: (a) landmarks, or (b) pixel intensities (iconic methods).

Landmarks are features in the image that are salient and easily recognizable. Landmarks can be features added extraneously during sample preparation or during acquisition, or unique features visible in both images. They can be selected automatically or manually. The minimum number of landmarks depends on the transformation model and the dimensionality: for the 2D case, a minimum of 3 points is necessary for an affine transformation, up to 4 for a projective transformation.
Automatic methods identify and match landmark points based on local image descriptors, such as SIFT ([[cite:&Lowe_1999]]) or SURF ([[cite:&Bay_2006]]). These methods are generally not suited to a multimodal task since the images enclose different types of information.
Manual methods involve the user intervention in selecting landmarks. They are used in the case of images with a large difference in terms of resolutions, or when it is not trivial to find similarities through the segmentation step. It is also the preferred method for partial registration, that it to say the registration of an image enclosing a subset of the tissue onto an image depicting a larger part of the tissue. [[cite:&Borodinov_2020]] register MALDI images onto a SIMS image by manually selecting matching pairs of fiducial markers done by the laser. [[cite:&Ryabchykov_2018]] register Raman images onto MALDI-MS images by manually selecting common features from PCA component images.

Iconic methods are based on pixel intensity similarities. The transformation parameters are modified iteratively until a local optimum of the similarity metric is reached.  The similarity metric measures the matching of two images after applying a deformation. Typical similarity metrics are the sum of squared differences (SSD) over both images, normalized cross-correlation, or mutual information, which estimates the statistical independence of the intensity distributions of two images. The SSD can be applied when both images have the same intensity range, as well as similar contrast. Normalized cross-correlation or mutual information should be used when images have different contrast or dynamic range.
The transformation parameters are updated by an optimization algorithm involving the similarity metric. For instance, linear gradient descent updates transformation parameters based on the slope of the metric. The resulting transformation strongly depends on the initialization parameters. The one-plus-one evolutionary method is a non-linear optimization algorithm, where transformation parameters are updated by selecting favorable mutations, that is to say modifications of the transformation parameters that improve the similarity [[cite:&Styner_2000]].  Mutations are defined by a probabilistic function which is modified during the optimization process.
Iconic methods are used in numerous MALDI-MSI registration tasks.  [[cite:&Anyz_2017]] align histological (H&E) and MALDI-MS images. Both images are different in terms of pixel intensities, so the authors extract binary masks of the sample. These masks are registered by an affine transformation, with an iterative gradient descent optimization of the SSD metric. [[cite:&Castellanos_Garcia_2021]] combine MALDI-MS with LA-ICP-MS images, so as to merge the extensive molecular information from MALDI with the better signal quality in LA-ICP-MS images. They select matching ion images manually in order to estimate both linear, and non-linear transformations. [[cite:&Abdelmoula_2019]]  register several 2D MALDI slices with a 3D MR image in order to obtain a volumetric representation of the MALDI dataset. The MALDI image is reduced by the t-SNE algorithm.  The corresponding 2D MR image is selected from the 3D volume manually. Then, both a linear and non-linear  registration methods are applied, using mutual information as a similarity metric.

Hybrid approaches use both iconic and landmark-based registration methods. [[cite:&Patterson_2018]] register microscopy and MALDI-MS images. Two microscopy images, before and after MALDI-MS imaging, are acquired. Since, they come from the same modality, the authors use iconic approaches to register them. The microscopy images are then registered onto an upsampled version of the MALDI-MS image using laser ablation marks as landmarks. This workflow avoids introducing deformation artefacts in the MSI datasets, and preserves the resolution of microscopy images.

The quality of the registration can be evaluated by various metrics, such as the Dice coefficient or the F-measure, which both estimate the proportion of overlapping pixels between the deformed and fixed images. When using non-linear transformations, it is important to select parameters such as to obtain a good compromise between shape matching and intensity fidelity. For instance, [[cite:&Grelard_2021]] estimate the shape matching by F-measure, and the intensity fidelity by computing the mutual information between the images before and after applying the non-linear registration.

bibliography:/home/fgrelard/org/bib/main.bib
