:PROPERTIES:
:ID:       2d7a5dea-9a2e-4bca-8543-e002c0f5f6ea
:END:
#+title: Group meeting December
#+filetags: :group_meeting:meeting:

* COVID pandemic
Meeting in remote.
Notify Caroline when working from home.
Lunch and social activities cancelled.

* Meetings
_Direction review_: postponed to 14th of January. Same organization for later.

Clean working place, when using reagents, solvents, etc. Not doing so can induce contamination.

* Equipment
Corinne: breakdown of QTrap. Waiting for the order. Should be done in the following days, weeks, ...

MALDI-TOF working properly.

* Projects
Region projects: application for one PhD candidate for early January.

ARCHE: currently building the website.
Researcher minister supposed to visit in New-York, maybe Bordeaux.

* Conferences
CBMN day prize for Michael.

EuPA: Nicolas is president of this society.

Young Proteomic Society, organization from the lab during middle of April.

* Human resources
Master student coming in January and February.

* Vaclav's presentation
/In a flash of light: X-ray free electron lasers meet native mass spectrometry./

Free electron laser (FEL): high energy pulses. Electrons undergo magnetic fields, undulate and emit photons.
_Application_: similar to synchrotron, femtosecond crystallography.


