:PROPERTIES:
:ID:       a0cf98b4-cd90-49fc-ba0a-60896e2770db
:END:
#+title: CATI
[[id:2dff42d8-b57a-4c3a-8619-3bfde728f67e][meeting]]

* <2021-11-23 Tue>
:PROPERTIES:
:ID:       5343a1a6-6c81-40b4-8828-1e863d25572a
:END:

[[id:24ef59cd-44ec-4f2c-90f6-f16d56dab7ac][multiblock]] [[id:99bf9725-eb93-4ec3-9c91-54eb9ad90686][statistical analysis]]

** Présentation de Marion Brandolini
Présentation générale.

Données multiblocs: données multivariées, multi-sources, souvent sur mêmes échantillons.
Plusieurs matrices 2D, une seule matrice 2D (plusieurs conditions expérimentales...)

_Principe:_ rechercher des variables latentes (combinaisons linéaires de variables initiales)

Pré-traitement des données:
1. Intrabloc: correction de dérive analytique, normalisation, standardisation des variables (ex: centrage-réduction)
2. Interblocs: Standardisation des blocs: pour éviter leurs différences de taille.

*** Multiblocs exploratoire
Décomposition des données en variables latentes: /scores/ et /loadings/. Prise en compte de l'information commune ou non.

Méthodes prenant en compte l'info commune:
- ACP multibloc, ou ACP consensus. Concaténation des blocs pré-traités et pondérés, puis ACP.
- CSWA ou ComDim: extraction /séquentielle/ des composantes maximisant la variance de la somme pondérée des matrices de variance covariances des différents blocs
- RGCSA: voir présentation suivante.
  
Méthodes prenant en compte l'info différente:
- Orthogonal2 PLS (O2PLS) dans le cas de 2 blocs
  espace de données dépourvu de l'espace en commun, uniquement l'information qui est propre aux blocs, puis commune.
- JIVE (Joint and Individual variances explained): idem à plus haut, sauf que d'abord info commune, puis distincte.

*** Multiblocs prédictif
Extraire l'info commune ou complémentaire pour la prédiction

- PLS multiblocs (MBPLS): régression PLS sur blocs prétraités pondérés concaténés
- PLS consensus ou hiérarchique (HPLS): ACP consens, normalisation des composantes globales, puis PLS.

