:PROPERTIES:
:ID:       1dfd714a-3b4c-4ef6-868b-aeeee112d68d
:END:
#+title: Imagerie et Spectroscopie Vibrationnelle
#+filetags: :raman:
[[id:34d764c4-4aad-4f1a-8194-fbceda6f6112][Conference]]

* Introduction Imagerie Raman
Raman [[id:14c33ce6-5427-4900-ae3d-0e00e286385d][spectroscopy]] and [[id:9a753b0f-254a-42cf-8ef4-9b139a0bd14f][imaging]].

* Apport de la résolution numérique de problèmes inverses à l'imagerie et la spectroscopie vibrationnelle
Saïd Moussaoui - LS2N

Inverse problems: acquisition system → measured signal.
There are perturbations in the measured signal.

Inverse problem: to go back from the measured signal to the information of interest.

$y = \kappa(x, e)$ ou $y = Kx + e$, $y$ measured signal, $e$ errors, $x$ information to recover. $K$ linear application.

Linear model: convolution (image restoration), mix (source separation), Radon transform (tomography)

Inversion: 3 conditions: stability, unicity, solution existence.

Regularized inversion: add hypotheses or information.
- Bayesian inference: (likelihood $\times$ /a priori/): *statistics*
- Minimization of a composite criterion (adjustment + penalization): *energy, variational*
  
  
  
