:PROPERTIES:
:ID:       5dc44257-c394-4234-bb72-00b893eb3e3d
:ROAM_REFS: cite:tyler22_denois_mass_spect_images_via
:END:
#+title: Denoising of mass spectrometry images via inverse maximum signal factors analysis
#+filetags: :★★★★☆:literature:

[[id:5edbbd59-853e-42ed-b750-87e292878ff8][Denoising]] [[id:fc865bc6-4c84-4d9f-8d67-21980ff47424][MSI]]

State-of-the-art methods based on MVA (Multivariate Analysis): PCA, NMF...
Remove the component images that represent noise from all ion images.
_Problem_: not always well defined (orthogonality constraint), number of components to choose...

_Proposed approach_: MSF (Maximal Signal Factors Analysis) based on [[id:8208b43a-a961-42d8-a878-4ba7b70837f0][MAF]]

MS image as matrix $X$. The covariance matrix can be written as:
\[
C_{total} = \frac{1}{n} (X - \mu) (X - \mu)^T
\]

If signal and noise are independent, we can write:
$C_{total} = C_{signal} + C_{bruit}$.

In MSF analysis, an estimation of $C_{bruit}$ is used to solve the  generalized eigenvalues problem:
\[
C_{total}w = \lambda C_{bruit} w
\]
where $\lambda$ eigenvalues, $w$ eigenvectors
$\lambda$ = squared signal to noise ratio

The denoised matrix $Y_k$ is given by:
\[
Y_k = S_i (C_{bruit} w_i)^T + \mu
\]

Estimation of $C_{bruit}$:
In MAF, difference between neighboring pixels.
Here, assumption: the variance in 2x2 bins is due to noise. The authors use coefficients from [[id:bc12621e-4ba9-43f7-ac9d-99ed69b4346f][the Haar wavelet]] transform (edge image).
It is more efficient than traditional MAF.


Problem: select the appropriate number of factors.
The authors propose five global and local criterion to assess the lack or goodness of fit metrics with different number of factors.
